name: 'Build'

permissions:
  contents: write

on: [push]

jobs:
    Build:
        runs-on: ubuntu-22.04
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v6
              with:
                fetch-depth: 0
            - uses: jiro4989/setup-nim-action@v2
            - run: rm */place*here
            - name: Download dependencies
              run: |
                curl -sL "https://github.com/electron/electron/releases/download/v42.6.0/electron-v42.6.0-linux-x64.zip" -o "electron/electron.zip"
                curl -sL "https://web.archive.org/web/20260704231758/https://partner.steamgames.com/downloads/steamworks_sdk_164.zip" -o "steamworks.zip"
            - name: Setup Steamworks
              run: |
                unzip -j steamworks.zip sdk/redistributable_bin/linux64/libsteam_api.so sdk/public/steam/lib/linux64/libsdkencryptedappticket.so -d greenworks/
                rm steamworks.zip
            - name: Setup electron
              run: |
                unzip electron/electron.zip -d electron/
                rm electron/electron.zip
            - name: Setup koffi
              run: |
                npm i koffi@2.15.2
                mkdir -p electron/resources/koffi/build/koffi/linux_x64/
                mv node_modules/koffi/build/koffi/linux_x64/koffi.node electron/resources/koffi/build/koffi/linux_x64/koffi.node
            - name: Compile
              run: nimble build --verbose -d:release
            - name: Bundle files
              run: tar -czvf nativeguessr.tar.gz nativecookie toolmanifest.vdf README.md LICENSE compatibilitytool.vdf greenworks/ electron/
            - uses: actions/upload-artifact@v6
              with:
                name: nativeguessr
                path: nativeguessr.tar.gz
            - name: Release
              if: startsWith(github.ref, 'refs/tags/')
              uses: softprops/action-gh-release@v2
              with:
                files: nativeguessr.tar.gz
                fail_on_unmatched_files: true
